package ke.co.mspace.nonsmppmanager.invalids;
// Generated May 12, 2017 1:31:55 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Tuserpaybill generated by hbm2java
 */
@Entity
@Table(name = "tUSERPAYBILL",
        catalog = "dbPAYMENTS"
)
public class Tuserpaybill implements java.io.Serializable {

    private Long id;
    private long tuserId;
    private int paybill;
    private String reply = "reply12345";
    private String email;
    private String defaultReply;
    private String callbackUrl;
    private boolean status;
    private String realStatus;
    private String callback_type;
    
    
    

    public Tuserpaybill() {
    }

    public Tuserpaybill(long tuserId, int paybill) {
        this.tuserId = tuserId;
        this.paybill = paybill;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Column(name = "tUSER_id", nullable = false)
    public long getTuserId() {
        return this.tuserId;
    }

    public void setTuserId(long tuserId) {
        this.tuserId = tuserId;
    }

    @Column(name = "paybill", nullable = false)
    public int getPaybill() {
        return this.paybill;
    }

    public void setPaybill(int paybill) {
        this.paybill = paybill;
    }

    @Column(name = "reply", nullable = true, length = 65535)
    public String getReply() {
        return reply;
    }

    public void setReply(String reply) {
        this.reply = reply;
    }

    @Column(name = "email", nullable = false, length = 100)
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "default_reply", nullable = false, length = 65535)
    public String getDefaultReply() {
        return defaultReply;
    }

    public void setDefaultReply(String defaultReply) {
        this.defaultReply = defaultReply;
    }

    @Column(name = "callback_url", updatable = true, nullable = true, columnDefinition = "VARCHAR(2000) DEFAULT ''")
    public String getCallbackUrl() {
        return callbackUrl;
    }

    public void setCallbackUrl(String callbackUrl) {
        this.callbackUrl = callbackUrl;
    }

    @Column(name = "status", nullable = false, updatable = true, columnDefinition = "tinyint DEFAULT 1")
    public boolean isStatus() {
        return status;
    }

    public void setStatus(boolean status) {
        this.status = status;
    }
    
    @Column(name = "callback_type")
    public String getCallback_type() {
        return callback_type;
    }

    public void setCallback_type(String callback_type) {
        this.callback_type = callback_type;
    }

    @Transient
    public String getRealStatus() {
        if (status == true) {
            realStatus = "Active";
        } else {
            realStatus = "Inactive";
        }
        return realStatus;
    }

    public void setRealStatus(String realStatus) {
        this.realStatus = realStatus;
    }

}
