name: Deploy to Tomcat

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Build WAR
      run: mvn clean package

    - name: Copy WAR to remote server (flattened)
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        source: target/cmaz.war
        target: /home/azureuser/deploy/
        strip_components: 1

    - name: Move WAR to Tomcat and Restart
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          if [ -f /home/azureuser/deploy/cmaz.war ]; then
            sudo mv /home/azureuser/deploy/cmaz.war /opt/tomcat/webapps/
            sudo systemctl restart tomcat
          else
            echo "WAR file not found in /home/azureuser/deploy"
            exit 1
          fi

